# Generated by Django 3.2 on 2021-05-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulación')),
                ('studen', models.CharField(max_length=50, verbose_name='')),
                ('comentary', models.TextField(verbose_name='Cometario')),
                ('note', models.IntegerField(max_length=2, verbose_name='Nota total')),
                ('datetitulation', models.DateTimeField(auto_now_add=True, verbose_name='Fecha titulción')),
                ('datematriculation', models.DateTimeField(verbose_name='Fecha matricuación')),
                ('estate', models.CharField(choices=[('publico', 'Publico'), ('oculto', 'Oculto')], default='borrador', max_length=15)),
            ],
            options={
                'ordering': ('-datetitulation',),
            },
        ),
    ]
