# Generated by Django 3.2 on 2021-05-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_alter_anuncio_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='datematriculation',
            field=models.DateTimeField(verbose_name='Fecha matriculción'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='datetitulation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha titulación'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='studen',
            field=models.CharField(max_length=50, verbose_name='Estudiante'),
        ),
    ]
