# Generated by Django 3.2 on 2021-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_auto_20210501_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='estate',
            field=models.CharField(choices=[('oculto', 'Oculto'), ('publico', 'Publico')], default='borrador', max_length=15),
        ),
    ]
