# Generated by Django 3.2 on 2021-05-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_alter_anuncio_estate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anuncio',
            options={'ordering': ('note', 'aprove', '-datetitulation')},
        ),
        migrations.AddField(
            model_name='anuncio',
            name='aprove',
            field=models.BooleanField(blank=True, default=False, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='estate',
            field=models.CharField(choices=[('publico', 'Publico'), ('oculto', 'Oculto')], default='borrador', max_length=15),
        ),
    ]
