# Generated by Django 3.2 on 2021-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_auto_20210501_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='photo',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='estate',
            field=models.CharField(choices=[('oculto', 'Oculto'), ('publico', 'Publico')], default='borrador', max_length=15),
        ),
    ]
