# Generated by Django 3.2 on 2021-05-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0008_alter_anuncio_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='estate',
            field=models.CharField(choices=[('oculto', 'Oculto'), ('publico', 'Publico')], default='oculto', max_length=15),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, verbose_name='Curso')),
                ('alumnos', models.IntegerField(verbose_name='Cantidad alumnos')),
                ('approved', models.IntegerField(verbose_name='Aprobados')),
                ('suspense', models.IntegerField(verbose_name='Suspensos')),
                ('alumnos_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anuncios.anuncio')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['name'],
            },
        ),
    ]
