# Generated by Django 3.2 on 2021-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0009_auto_20210516_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Curso'),
        ),
    ]
