# Generated by Django 3.2 on 2021-05-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0013_alter_anuncio_estate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anuncio',
            new_name='Alumno',
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ('note', 'aprove', '-datetitulation'), 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiante'},
        ),
    ]
