# Generated by Django 3.2 on 2021-05-27 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0014_auto_20210527_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25, verbose_name='Nombre')),
                ('photo', models.ImageField(null=True, upload_to='images', verbose_name='Foto')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('description', models.TextField(verbose_name='Descrición')),
                ('anyos_open', models.IntegerField(verbose_name='En servicio')),
            ],
            options={
                'verbose_name': 'Instituto',
                'verbose_name_plural': 'Institutos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ('note', 'aprove', '-datetitulation'), 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estate',
            field=models.CharField(choices=[('oculto', 'Oculto'), ('publico', 'Publico')], default='oculto', max_length=15),
        ),
        migrations.AddField(
            model_name='curso',
            name='center_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anuncios.school', verbose_name='Instituto'),
        ),
    ]
